theme: jekyll-theme-minimal
title: CM22012 homepage
description: Bookmark this to track new content as it is published.
Github pages is being used to publish accessible content (HTML) this year because the previous location - staff personal public webpages - were removed by the University during summer 2026, necessitating finding an alternative hosting solution.
